package com.example.kotlintest

object NavDestination {
    const val CALL_SCREEN = "CALL_SCREEN"
    const val POCT_SCREEN = "POCT_SCREEN"
    const val HOME_SCREEN = "HOME_SCREEN"
    const val THERMOMETER_SCREEN = "THERMOMETER_SCREEN"
    const val PULSE_OXIMETER_SCREEN = "PULSE_OXIMETER_SCREEN"
    const val TONOMETER_SCREEN = "TONOMETER_SCREEN"
    const val ECG_SCREEN = "ECG_SCREEN"
    const val STETHOSCOPE_SCREEN = "STETHOSCOPE_SCREEN"
    const val WHITE_BLOOD_CELL_ANALYZER_SCREEN = "WHITE_BLOOD_CELL_ANALYZER_SCREEN"
    const val SPIROMETER_SCREEN = "SPIROMETER_SCREEN"
}